=== UO277303/SEW-2022-23/UO277303-practica2/Ejercicio-1/Tarea-2/redSocial.dtd
<!ELEMENT persona (datos, foto+, video*, comentario, (persona, persona, persona)?)>
<!ELEMENT datos (fechaNac, lugarNac, coordNac, lugarRes, coordRes)>
<!ELEMENT fechaNac (#PCDATA)>
<!ELEMENT lugarNac (#PCDATA)>
<!ELEMENT coordNac (latitud, longitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT lugarRes (#PCDATA)>
<!ELEMENT coordRes (latitud, longitud, altitud)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>
<!ATTLIST persona nombre CDATA #REQUIRED>
<!ATTLIST persona apellidos CDATA #REQUIRED>

=== UO277303/SEW-2022-23/PRACTICA-3/Ejercicio-12/Ejercicio12.xml
<?xml version= "1.0" encoding = "UTF-8" ?>
<!DOCTYPE persona SYSTEM "redSocial.dtd">

<persona nombre="Héctor" apellidos="Lavandeira Fernández">

	<datos>
		<fechaNac>2001-12-25</fechaNac>
		<lugarNac>Ponferrada, León</lugarNac> 
		<coordNac>
			<latitud>-6.537778</latitud>
			<longitud>42.534167</longitud>
			<altitud>544</altitud>
		</coordNac>
		<lugarRes>Oviedo, Asturias</lugarRes>
		<coordRes>
			<latitud>-5.849167</latitud>
			<longitud>43.36</longitud>
			<altitud>232</altitud>
		</coordRes>
	</datos>
	<foto>multimedia/foto/1.jpg</foto>
	<video>multimedia/video/1.mp4</video>
	<comentario>Comentario de Héctor Lavandeira</comentario>
    
</persona>
